name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
  merge_group: # GitHub Merge Queue

concurrency:
  # Skip intermediate builds: all builds except for builds on the `master` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: read
  actions: write # Needed for `julia-actions/cache` to clear old caches

env:
  aws_region: us-east-1
  s3_bucket: julialang2

jobs:
  package-tests:
    name: Package tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.6"
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - uses: julia-actions/setup-julia@4c0cb0fce8556fdb04a90347310e5db8b1f98fb9 # v2.7.0
        with:
          version: ${{ matrix.version }}

      - uses: julia-actions/cache@9a93c5fb3e9c1c20b60fc80a478cae53e38618a4 # v3.0.2

      - name: Install dependencies
        run: julia --color=yes --project -e "using Pkg; Pkg.instantiate()"

      - uses: julia-actions/julia-runtest@d60b785c6f2bdf4ebfb18b2b6f7d93b7dfb0efe3 # v1.11.4

  full-test:
    name: Full test
    # This job takes a long time (1+ hours).
    # So we intentionally skip this job on PR runs.
    # But we still run this job on Merge Queue jobs.
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - uses: julia-actions/setup-julia@4c0cb0fce8556fdb04a90347310e5db8b1f98fb9 # v2.7.0
        with:
          version: "1.6"

      - uses: julia-actions/cache@9a93c5fb3e9c1c20b60fc80a478cae53e38618a4 # v3.0.2

      - name: Install dependencies
        run: julia --color=yes --project -e "using Pkg; Pkg.instantiate()"

      - run: rm -f versions.json

      - name: Build versions.json
        run: |
          using VersionsJSONUtil

          VersionsJSONUtil.main("versions.json")
        shell: julia --project {0}

      - name: Validate versions.json against schema
        run: npx -p ajv-cli@3.3.0 ajv -s schema.json -d versions.json

      - run: julia --project test/more_tests.jl versions.json

      - name: Upload versions.json as workflow artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: versions
          path: versions.json
          if-no-files-found: error

  upload-to-s3:
    needs: [package-tests, full-test]
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Download versions.json from previous job
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: versions

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # 6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Upload versions.json to S3
        run: aws s3 cp versions.json s3://${{ env.s3_bucket }}/bin/versions.json --acl public-read --no-progress

      - name: Purge cache
        run: curl -X PURGE https://julialang-s3.julialang.org/bin/versions.json
